name: Deploy Kubernetes Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Copy Kubernetes files
        run: |
          mkdir -p kubernetes
          cp /mnt/c/Users/HP/Downloads/kubernetes-work/kubernetes/* kubernetes/

      - name: Commit and push changes
        run: |
          git add kubernetes/*
          git commit -m "Deploy Kubernetes files"
          git push